apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 793524670633.dkr.ecr.ap-south-1.amazonaws.com/backend_repo:38e18068d449e65361febac61e97e0f14f10a435
        ports:
        - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 793524670633.dkr.ecr.ap-south-1.amazonaws.com/frontend_repo:38e18068d449e65361febac61e97e0f14f10a435
        ports:
        - containerPort: 80
